const test = require('./test-runner')

test('assignation')()
test('parens-1')()
test('parens-2')()
test('parens-3')()
test('right-parens')()
test('semi-arrow')()
test('semi-opening-parens')()
test('semi-opening-curly')()
test('semi-coma')()
test('semi-following-bracket')()
test('semi-keep-leading')()
test('curly-spacing')()
